import { Metadata } from "next";
import Link from "next/link";
import prisma from "@/lib/db";
import { Breadcrumbs } from "@/components/seo/Breadcrumbs";
import { Calendar, TrendingUp, BarChart3, Fuel } from "lucide-react";

export const revalidate = 300;

const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL || "https://trafico.live";

export const metadata: Metadata = {
  title: "Informes de tráfico y combustible — trafico.live",
  description:
    "Informes diarios, semanales y mensuales de tráfico, precios de combustible y siniestralidad vial en España. Datos oficiales de DGT, AEMET y MITERD.",
  alternates: { canonical: `${BASE_URL}/informes` },
  openGraph: {
    title: "Informes de tráfico y combustible",
    description:
      "Análisis de tráfico, precios de combustible y siniestralidad vial.",
    url: `${BASE_URL}/informes`,
    siteName: "trafico.live",
    type: "website",
  },
};

const REPORT_SECTIONS = [
  {
    title: "Informes diarios de tráfico",
    description: "Resumen diario de incidencias, precios y meteorología",
    href: "/informes/nacional",
    icon: Calendar,
    category: "DAILY_REPORT" as const,
  },
  {
    title: "Informes de combustible",
    description: "Precios diarios de gasóleo y gasolina con ranking provincial",
    href: "/informes/combustible",
    icon: Fuel,
    category: "PRICE_ALERT" as const,
  },
  {
    title: "Resúmenes semanales",
    description: "Tendencias semanales de tráfico y precios",
    href: "/informes/semanal",
    icon: TrendingUp,
    category: "WEEKLY_REPORT" as const,
  },
  {
    title: "Análisis mensuales",
    description: "Siniestralidad, combustible e infraestructura",
    href: "/informes/mensual",
    icon: BarChart3,
    category: "MONTHLY_REPORT" as const,
  },
];

export default async function InformesPage() {
  const recentArticles = await prisma.article.findMany({
    where: {
      status: "PUBLISHED",
      isAutoGenerated: true,
      category: {
        in: [
          "DAILY_REPORT",
          "WEEKLY_REPORT",
          "PRICE_ALERT",
          "FUEL_TREND",
          "MONTHLY_REPORT",
        ],
      },
    },
    orderBy: { publishedAt: "desc" },
    take: 10,
    select: {
      slug: true,
      title: true,
      category: true,
      publishedAt: true,
      summary: true,
    },
  });

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-950">
      <main className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <Breadcrumbs
          items={[
            { name: "Inicio", href: "/" },
            { name: "Informes", href: "/informes" },
          ]}
        />

        <h1 className="text-3xl sm:text-4xl font-bold text-gray-900 dark:text-gray-100 mb-4 font-heading">
          Informes de tráfico y combustible
        </h1>
        <p className="text-lg text-gray-600 dark:text-gray-400 mb-10 max-w-3xl">
          Análisis automáticos con datos oficiales de la DGT, AEMET y el
          MITERD. Actualizados diariamente.
        </p>

        {/* Section cards */}
        <div className="grid sm:grid-cols-2 gap-6 mb-12">
          {REPORT_SECTIONS.map((section) => (
            <Link
              key={section.href}
              href={section.href}
              className="bg-white dark:bg-gray-900 rounded-xl border border-gray-200 dark:border-gray-800 p-6 hover:border-tl-300 dark:hover:border-tl-700 transition-colors group"
            >
              <div className="flex items-start gap-4">
                <div className="p-2 bg-tl-50 dark:bg-tl-950/30 rounded-lg">
                  <section.icon className="w-6 h-6 text-tl-600 dark:text-tl-400" />
                </div>
                <div>
                  <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100 group-hover:text-tl-600 dark:group-hover:text-tl-400 transition-colors">
                    {section.title}
                  </h2>
                  <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">
                    {section.description}
                  </p>
                </div>
              </div>
            </Link>
          ))}
        </div>

        {/* Recent reports */}
        <h2 className="text-xl font-semibold text-gray-900 dark:text-gray-100 mb-4">
          Últimos informes
        </h2>
        <div className="space-y-3">
          {recentArticles.map((article) => (
            <Link
              key={article.slug}
              href={`/noticias/${article.slug}`}
              className="block bg-white dark:bg-gray-900 rounded-lg border border-gray-200 dark:border-gray-800 p-4 hover:border-tl-300 dark:hover:border-tl-700 transition-colors"
            >
              <div className="flex items-start justify-between gap-4">
                <div>
                  <h3 className="text-sm font-medium text-gray-900 dark:text-gray-100">
                    {article.title}
                  </h3>
                  <p className="text-xs text-gray-500 dark:text-gray-400 mt-1 line-clamp-1">
                    {article.summary}
                  </p>
                </div>
                <time
                  dateTime={article.publishedAt.toISOString()}
                  className="text-xs text-gray-400 dark:text-gray-500 whitespace-nowrap"
                >
                  {article.publishedAt.toLocaleDateString("es-ES", {
                    day: "numeric",
                    month: "short",
                  })}
                </time>
              </div>
            </Link>
          ))}
        </div>
      </main>
    </div>
  );
}
